# Generated by Django 5.1.6 on 2025-12-31 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='department',
            field=models.CharField(blank=True, choices=[('MBA', 'Master of Business Administration'), ('BBA', 'Bachelor of Business Administration'), ('BCOM', 'Bachelor of Commerce'), ('BCA', 'Bachelor of Computer Applications'), ('MCOM', 'Master of Commerce')], help_text='Student Department at Registration', max_length=5, null=True),
        ),
    ]
