# Generated by Django 5.1.6 on 2025-12-30 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('department', models.CharField(choices=[('MBA', 'Master of Business Administration'), ('BBA', 'Bachelor of Business Administration'), ('BCOM', 'Bachelor of Commerce'), ('BCA', 'Bachelor of Computer Applications'), ('MCOM', 'Master of Commerce')], max_length=5)),
                ('passed_out_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('MBA', 'Master of Business Administration'), ('BBA', 'Bachelor of Business Administration'), ('BCOM', 'Bachelor of Commerce'), ('BCA', 'Bachelor of Computer Applications'), ('MCOM', 'Master of Commerce')], max_length=5)),
                ('joining_year', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
